# Generated by Django 4.1.4 on 2022-12-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_rename_authot_ad_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='adress',
            new_name='address',
        ),
    ]
